### PR TITLE
Added article read chart

### PR DESCRIPTION
**Pull request by mmockett**
@wheresrhys - Added a chart to show number of articles 'read' as a percentage of total article views. Am I right in thinking page:attention is either true or false? If not, this query is nonsense.

### CODE REVIEW

**Comment by wheresrhys** [comment]
You're not right, but we could add something like attention/ word count x
n > 0.5 to roughly indicate they probably read half. Nice direction to
think in

On Friday, 19 February 2016, Max Mockett <notifications@github.com> wrote:

> @wheresrhys <https://github.com/wheresrhys> - Added a chart to show
> number of articles 'read' as a percentage of total article views. Am I
> right in thinking page:attention is either true or false? If not, this
> query is nonsense.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Financial-Times/next-beacon-v2/pull/65
> Commit Summary
>
>    - Added article read chart
>
> File Changes
>
>    - *M* server/middleware/dashboards/googlesearch.yml
>    <https://github.com/Financial-Times/next-beacon-v2/pull/65/files#diff-0>
>    (7)
>
> Patch Links:
>
>    - https://github.com/Financial-Times/next-beacon-v2/pull/65.patch
>    - https://github.com/Financial-Times/next-beacon-v2/pull/65.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-beacon-v2/pull/65>.
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by adambraimbridge** [comment]
By coincidence there's a conversation about 'attention' in the #editorial-tech channel in slack. This is an interesting article: http://upworthy.github.io/2014/06/implementing-attention-minutes-part-1/

**Comment by mmockett** [comment]
Interesting - would be nice to see something consistent used across beacon / lantern - we could even use it as a replacement for counted content consumption eventually, which at the moment is pretty basic (think it's just based on clicks).

**Comment by wheresrhys** [comment]
Lantern uses the same attention we do. AFAIK they only have it for article read on next as on ft.com there's nothing implemented. Attention deficit

**Comment by adambraimbridge** [comment]
It goes beyond just attention, by the way... here's a braimdump from last year … casting a wider net than just whether articles are being “used correctly”, asking "how can we tell if/how _any_ feature’s being utilised"?
image

**Pull request closed without merging**
